apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-demo
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: spring-demo
  ports:
    - name: http
      port: 80          # Standard HTTP port externally
      targetPort: 8080  # Your app's internal port
      protocol: TCP
  externalTrafficPolicy: Local